### ISSUE TITLE
Unexpected behavior of the cross-pol radar calculations

### ISSUE THREAD

**Issue by DaveOri** [igmk/pamtra#10]
A user reported an unexpected behavior of the radar calculations using cross_pol channels.
Basically what happens is that regardless of the dictated polarization the code produces always the same reflectivity values.

This happens with Mie and with tmatrix with ar=1 for wich it should be trivial that the cross-pol component is null.

I will make some tests to have a better picture of what is going on. On next post I will give a minimal code example on how to reproduce the problem.

Once solved, we should provide an example code on how to make radar spectral simulation with polarization.

**Comment by akiohansen** [comment]
Perhaps the DualPol example could be helpful to investigate this in more detail with the modification of setting the aspect ratio of the example ice hydrometeors to 1.0, see: https://github.com/igmk/pamtra/blob/master/examples/pyPamTest_radarDualPol.py

Thank you very much for all your help!

**Comment by DaveOri** [comment]
There are multiple orders of problems related to this issue:
1) Mie and other spherical-like scattering solvers does not assume polarization and give the same reflectivity to all pol state. This is wrong for cross-pol states for which the reflectivity should be 0. A quick fix will be soon released and would solve this issue
2) Other problems related to this opened during the debugging (VH state causes errors when used with tmatrix and HV basically gives the same value as HH). I will open a separate issue for them and I also have a workaround under testing

**Comment by DaveOri** [comment]
Fixed by 6bdec67b6f68a345272f33a74c342232e77fc664
