### ISSUE TITLE
radar_airmotion_model defaults to 'step'

### ISSUE THREAD

**Issue by DaveOri** [igmk/pamtra#18]
As in the subject, the default value for the namelist setting radar_airmotion_model is 'step'
This creates unwanted bimodalities in the spectra.

I do not see a useful (physical) case scenario where this is the behavior to replicate
I suggest switching the default to 'constant' which (to me) represents what a user expects to happen if the vertical air motion is set as input parameter

**Comment by maahn** [comment]
Well it makes sense if you want to simulate strong up/downdrafts and non-uniform beam-filling. But I agree that this is a rather exotic case and the default should be constant.

**Comment by DaveOri** [comment]
closed by 36ab409dd7464661acb908bbe10ebb3b521c9501
