### ISSUE TITLE
Where is subroutune gasabsr98 defined?

### ISSUE THREAD

**Issue by MeraX** [igmk/pamtra#23]
Dear all,

can somebody explain the magic behind gasabsr98 to me?
It is called here:
https://github.com/igmk/pamtra/blob/f104990169bf76e139bddc0494da7df496f50ef0/src/get_atmosG.f90#L51
But that is also the only place where I can find the string "gasabsr98" in this repository. How does that work?

**Comment by DaveOri** [comment]
My feeling is that you are looking at old code. get_atmosG is not called by anywhere in the code.
The current implementation calls rosen98_gasabs from get_gasabs by run_rt
If you are interested in calling the gasabs module directly I have also made available a python tool in the tool folder

**Comment by MeraX** [comment]
brilliant. That was exactly, what I was looking for. I will have a look in the tools.

**Comment by MeraX** [comment]
I just extended the tool to plot individual gaseous absorption coefficients. Is it okay to put then into the respective tool folder or better to some examples folder?
https://github.com/igmk/pamtra/blob/master/tools/pyGasAbs/plot_abs_spectrum.py

**Comment by DaveOri** [comment]
probably better to leave it in the tools. The example folder contains more use-case scenarios of the whole package. The tools folder is more for low-level interaction with the components of pamtra, analysis and debugging. We cannot guarantee that they will always compile and operate properly, in fact, they are not installed during the main build process of pamtra. The tool folder was left unmaintained and not functioning for quite a long time and revived just recently. I would prefer that the examples/ folder contain always script that run properly.

**Comment by DaveOri** [comment]
@MeraX can we close this rather old issue?
