### ISSUE TITLE
LIDAR depolarization ratio as output

### ISSUE THREAD

**Issue by VeeramanikandanR** [igmk/pamtra#32]
Hi,
I would like to derive the LIDAR depolarization ratio as an output from PAMTRA. 
I couldn't find a similar parameter in the code so far. Could someone please help me with how to achieve this?
Thanks and Regards,
Veera

**Comment by DaveOri** [comment]
Hi Veera.
PAMTRA is only a microwave simulator so far.
Other forward operators like CR-SIM also provide LIDAR simulation capabilities.

You will not get this quantity out of PAMTRA in the near future. PAMTRA focuses on flexibility and internal consistency, which is achieved through a careful implementation of all of its components.
A LIDAR simulator requires, at least, to model the scattering properties of hydrometeors in the visible spectrum. Currently, available models are not fully consistent with the assumptions made in the microwave. This brings the need to adopt further assumptions for the LIDAR only and make a separate simulator that works in parallel with PAMTRA.

Thanks for your issue, we will consider extending PAMTRA to different remote sensing instruments (including LIDARs) in the future.
Davide

**Comment by VeeramanikandanR** [comment]
Hi Davide,
Thank you for your comments.
Thanks and Regards,
Veera
