### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by yuerchang** [igmk/pamtra#34]
Eventually, you can build the documentation by using the Makefile in the PAMTRA main directory with

make html 

error:  could not import extension sphinx.ext.autosectionlabel

What can I do? How to install it?

**Comment by DaveOri** [comment]
Hi,
It seems a problem related to the sphinx version you have installed and not sphinx itself.
I have tried to install pamtra on a fresh installation of Ubuntu 20.04 and everything works fine with sphinx 1.8.5

Could you check which sphinx version you have installed by running the following command?
`python3 -c "import sphinx; print(sphinx.__version__)" `

You can also try to upgrade sphinx, or to pin the version 1.8.5 and see if that helps

In any case, the documentation is available online on readthedocs at
[https://pamtra.readthedocs.io/en/latest/](https://pamtra.readthedocs.io/en/latest/)

**Comment by DaveOri** [comment]
@yuerchang  is this still an issue?
