### ISSUE TITLE
pamtra_create_RT4_files.py. The purpose is to simulate microwave TB from the top of the atmosphere for a radiometer

### ISSUE THREAD

**Issue by sismasamuel** [igmk/pamtra#37]
I tried to run _**pamtra_create_RT4_files.py**_. The purpose is to simulate microwave TB from the top of the atmosphere for a radiometer. How to proceed. But the output is showing an error why

WARNING:  info= 2
WARNING:  info= 2
WARNING:  info= 2
WARNING:  info= 2
CONVERGENCE IS NOT OBTAINED FOR NPN1=100.  EXECUTION TERMINATED
 2022/10/11  09:57:56  fatal   in module tmatrix_amplq
     CONVERGENCE IS NOT OBTAINED FOR NPN1
 2022/10/11  09:57:56  fatal   in module tmatrix_calc_single
     error in tmatrix_amplq!
 2022/10/11  09:57:56  fatal   in module tmatrix_calc
     error in calc_single_tmatrix!
 2022/10/11  09:57:56  fatal   in module calc_scatProperties
     error in calc_tmatrix!
 2022/10/11  09:57:56  fatal   in module hydrometeor_extinction
     Error in calc_scatProperties
 2022/10/11  09:57:56  fatal   in module run_rt
       error in run_drop_size_dist!    1     1
 2022/10/11  09:57:56  fatal   in module run_pamtra
     Error in run_rt!
Traceback (most recent call last):
  File "pamtra_create_RT4_files.py", line 22, in <module>
    pam.runPamtra(89.0)
  File "/home/nizy/lib/python/pyPamtra/core.py", line 1490, in runPamtra
    raise RuntimeError('Fortran code failed')
RuntimeError: Fortran code failed'

**Comment by mariomech** [comment]
How did you run it? Did the pamtra package compile without any error? did you do it with the same python major version (2 or 3) as you used for executing pamtra_create_RT4_files.py?

Anyway, the script you try to execute does not what you want to do. It only creates an example input file that can b used with the original RT4 fortran code provided by Frank Evans.

**Comment by sismasamuel** [comment]
I wish to simulate microwave Tb on top of the atmosphere for 183.31 GHz over a region. I have insitu measurment of vertical profile of temperature and relative humidity. How can I calculate Tb on top of atmosphere? I am using the python 3 versions. How can I do that? is any documentation is avilable? I am a research student, kindly consider.

I am able to run the examples in the python code(python radarSpec_howto.py etc.) and simulate the gaseous absorption spectrum using the Rosenkrans model (/pamtra/tools/pyGasAbs/plot_abs_spectrum.py). 

How can i confirm that the pamtra package compile without any error?

**Comment by mariomech** [comment]
Since the examples work, PAMTRA should be fine.

A simple example for passsive simulations on top of the atmosphere can be found [here](https://github.com/igmk/pamtra/blob/master/examples/simple_passive.ipynb)
