### ISSUE TITLE
how to understand input example_ocean.lay data variables

### ISSUE THREAD

**Issue by mannilhouse** [igmk/pamtra#40]
I tried to run simple_passive.ipynb, i am able to generate tb on top of atmosphere. The description of variables in input file I am not able to get exactly. The input example_ocean.lay has height, pressure, temp, relative humidity, the rest 5 columns I am not able to understand the same.  
Where is the input data read or is there any fortran code to read example_ocean.lay

**Comment by mariomech** [comment]
The five columns correspond to the mass mixing ratios of the hydrometeors in the same order as listed in the descriptor file.

The input file is read bby the routine _read_new_fill_variables_ which can be found in [vars_atmosphere.f90](https://github.com/igmk/pamtra/blob/9a3e85ff23ee284c6745f41cec0b5f3ce7042093/src/vars_atmosphere.f90)
