### ISSUE TITLE
simulate weighting function of amsu channels

### ISSUE THREAD

**Issue by sismasamuel** [igmk/pamtra#41]
can i simulate weighting functions for any radiometers such as saphir or amsu like in https://tropic.ssec.wisc.edu/real-time/amsu/explanation.html

**Comment by mariomech** [comment]
Dear sismasamuel,
the simulation of weighting function is not supported by PAMTRA although the maths and physics it is in there. THis needs to be done by own scripts or programs.
Best Mario
