### ISSUE TITLE
MacOS Segfault when building

### ISSUE THREAD

**Issue by ephraims28** [igmk/pamtra#44]
Hi,
I am in the process of building PAMTRA and ran into a segfault that I've been unable to resolve. Attached is my terminal screen. I hypothesize it has something to do with gcc because this is the first step in the Makefile that uses gcc.

There are also out of bounds indexing errors before the segfault that may or may not be related to my problem. And I don't know why those warnings are occurring since I didn't modify the code

.
<img width="681" alt="Screen Shot 2023-06-01 at 4 18 02 PM" src="https://github.com/igmk/pamtra/assets/78697048/f2ddb6a4-0dc5-4053-b0b0-4ccbefc191d0">

Thanks,
Sam Ephraim

**Comment by jchylik** [comment]
>  ran into a segfault 

However this is not a runtime segmentation fault, but segmentation fault during compilation. So it might indicate that compilers or linkers are not installed correctly.

>  Attached is my terminal screen.

Instead of a screenshot, a text output would be more helpful.

**Comment by ephraims28** [comment]
Yeah, I think it's issue with my gcc. I get a segfault even when just running "gcc --version". I think it's similar to this issue. (https://github.com/Homebrew/homebrew-core/issues/126054)

I'll work on finding a fix, but if you know what is happening, help would be appreciated!

(base) MacBook-Air-36:pamtra samephraim$ gcc --version
Segmentation fault: 11

(base) MacBook-Air-36:pamtra samephraim$ brew info gcc
==> gcc: stable 13.1.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/13.1.0 (1,606 files, 429.5MB) *
  Poured from bottle on 2023-06-01 at 11:15:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0-or-later with GCC-exception-3.1
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 220,781 (30 days), 6,151 (90 days), 993,848 (365 days)
install-on-request: 60,178 (30 days), 3,755 (90 days), 486,057 (365 days)
build-error: 195 (30 days)


(base) MacBook-Air-36:pamtra samephraim$ make
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/kinds.f90 -o src/kinds.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/nan.f90 -o src/nan.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/vars_index.f90 -o src/vars_index.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/report_module.f90 -o src/report_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/rt_utilities.f90 -o src/rt_utilities.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/settings.f90 -o src/settings.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/constants.f90 -o src/constants.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/zlib_stuff.f90 -o src/zlib_stuff.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/mod_fastem4_coef.f90 -o src/mod_fastem4_coef.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/gasabs_module.f90 -o src/gasabs_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/conversions.f90 -o src/conversions.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/descriptor_file.f90 -o src/descriptor_file.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/vars_atmosphere.f90 -o src/vars_atmosphere.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/vars_rt.f90 -o src/vars_rt.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/vars_hydroFullSpec.f90 -o src/vars_hydroFullSpec.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/mod_io_strings.f90 -o src/mod_io_strings.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/getopt.f90 -o src/getopt.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/parse_options.f90 -o src/parse_options.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/radmat.f90 -o src/radmat.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/convolution.f90 -o src/convolution.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/get_gasabs.f90 -o src/get_gasabs.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/vars_output.f90 -o src/vars_output.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/azimuth_emissivity_module.f90 -o src/azimuth_emissivity_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/hyperbolic_step.f90 -o src/hyperbolic_step.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/slope_variance.f90 -o src/slope_variance.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/reflection_correction_module.f90 -o src/reflection_correction_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/large_scale_correction_module.f90 -o src/large_scale_correction_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/small_scale_correction_module.f90 -o src/small_scale_correction_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/foam_utility_module.f90 -o src/foam_utility_module.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/liu.f90 -o src/liu.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/fresnel.f90 -o src/fresnel.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/fastemx.f90 -o src/fastemx.o
src/fastemx.f90:287:17:

  287 |       emissivity(u_idx)  = e_azimuth(u_idx) ! knwon Warning: Array reference is out of bounds (3 > 2) in dimension 1
      |                 1
Warning: Array reference at (1) is out of bounds (3 > 2) in dimension 1
src/fastemx.f90:287:37:

  287 |       emissivity(u_idx)  = e_azimuth(u_idx) ! knwon Warning: Array reference is out of bounds (3 > 2) in dimension 1
      |                                     1
Warning: Array reference at (1) is out of bounds (3 > 2) in dimension 1
src/fastemx.f90:288:17:

  288 |       emissivity(v_idx)  = e_azimuth(v_idx) ! knwon Warning: Array reference is out of bounds (4 > 2) in dimension 1
      |                 1
Warning: Array reference at (1) is out of bounds (4 > 2) in dimension 1
src/fastemx.f90:288:37:

  288 |       emissivity(v_idx)  = e_azimuth(v_idx) ! knwon Warning: Array reference is out of bounds (4 > 2) in dimension 1
      |                                     1
Warning: Array reference at (1) is out of bounds (4 > 2) in dimension 1
src/fastemx.f90:293:37:

  293 |     if (nstokes .gt. 2) reflectivity(u_idx:v_idx) = zero   ! 3rd, 4th stokes from atmosphere are not included. ! knwon Warning: Lower array reference is out of bounds (3 > 2) in dimension 1
      |                                     1
Warning: Lower array reference at (1) is out of bounds (3 > 2) in dimension 1
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/tessem2.f90 -o src/tessem2.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/ocean_sfc_optics.f90 -o src/ocean_sfc_optics.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/mod_mwatlas_nt_bin.f90 -o src/mod_mwatlas_nt_bin.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/telsem2.f90 -o src/telsem2.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/land_sfc_optics.f90 -o src/land_sfc_optics.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/sfc_optics.f90 -o src/sfc_optics.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/sfc_matrices.f90 -o src/sfc_matrices.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/run_rt.f90 -o src/run_rt.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/scat_utilities.f90 -o src/scat_utilities.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/mpm93.f90 -o src/mpm93.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/eps_water.f90 -o src/eps_water.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/mie_scat_utilities.f90 -o src/mie_scat_utilities.o
gfortran  -c -fPIC -cpp -Jsrc/ -Isrc/  -O2 src/mie_spheres.f90 -o src/mie_spheres.o
gcc  -O  -fPIC -c src/scatdb.c -o src/scatdb.o
make: *** [src/scatdb.o] Segmentation fault: 11

**Comment by jchylik** [comment]
> Yeah, I think it's issue with my gcc. I get a segfault even when just running "gcc --version". I think it's similar to this issue. 
> (https://github.com/Homebrew/homebrew-core/issues/126054)

I have no experience with Mac, but it seem the issue is either that additional compiler flags are required on Mac, or just that the gcc is badly installed on Mac.

>  (base) MacBook-Air-36:pamtra samephraim$ make

As for the rest of the code, it is doing pretty much what is expected of it.

**Comment by jchylik** [comment]
> ```
> ld: warning: directory not found for option '-L../lib/'
> ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/lib
> ```

It looks like you would need to check paths with the location of libraries and modify some parts of Makefile file
