### ISSUE TITLE
Remove hard-coded ~/lib/python/ in py_usStandard Makefile

### ISSUE THREAD

**Issue by martin-rdz** [igmk/pamtra#49]
## Issue
Modifications of `PYINSTDIR` are not propagated down to the sub-make of py_usStandard.
 
## Fix
Use the `export` of make variables (https://www.gnu.org/savannah-checkouts/gnu/make/manual/html_node/Variables_002fRecursion.html)

Change in pamtra makefile
```
PYINSTDIR := ~/lib/python/
export PYINSTDIR
```

and in `tools/py_usStandard/Makefile`:
```
install: usStandardAtmosphere.so
     cp *.py $(PYINSTDIR)
     cp *.so $(PYINSTDIR)
```

**Comment by DaveOri** [comment]
Hi Martin, I was working on a more pressing issue #52 whose current solution in branch mesonpy would automatically solve also this issue.
Cheers,
Davide

**Comment by maahn** [comment]
Fixed because we finally got rid of the py_usStandard submodule aa8fa3874adb679c1d7c559ebece018d6ed778f8
