### ISSUE TITLE
Issue compiling on Macbook Pro ARM64 architecture

### ISSUE THREAD

**Issue by josephko91** [igmk/pamtra#56]
I am trying to compile pamtra according to the [Mac instructions on the doc](https://pamtra.readthedocs.io/en/latest/installation.html#get-model-from-git-repository), but I'm running into issues. 

My mac specs: 
- Macbook Pro 2023
- M2 Pro chip
- macOS Sonoma 14.5

I've installed gcc, fftw, and netcdf with brew as suggested in the doc. Then I created a conda environment and installed pandas numpy scipy matplotlib netcdf4 on that conda environment. I added the lib and include paths for the conda env for the -I and -L flags in the makefile. The specific changes were made to the lines below:

`FCFLAGS=-c -fPIC -cpp -J$(OBJDIR) -I$(OBJDIR) -I/Users/josephko/miniconda3/envs/pamtra/include`
`LFLAGS := -L/usr/lib/ -L/usr/local/lib/ -L/opt/homebrew/lib/ -L/Users/josephko/miniconda3/envs/pamtra/lib -llapack -L$(LIBDIR) -L../$(LIBDIR) -lblas -lz -lfftw3`

I'm getting a "Undefined symbols for architecture arm64:" error. See attached for full output. 

Any ideas how to fix this? Any help greatly appreciated :)
[make_output_01.txt](https://github.com/user-attachments/files/17838121/make_output_01.txt)

**Comment by DaveOri** [comment]
Hi Joseph,
thanks for reporting this. I am not a MAC user and I don't have an apple silicon at hand to try to reproduce your issue.
I can only see that the missing symbols are related to netcdf. I can only suggest to see if there are specific netcdf libraries for ARM64. I found this resource online https://formulae.brew.sh/formula/netcdf-fortran
But really, I am heavily guessing here.
Another option would be to try to compile the netcdf shared library yourself

**Comment by maahn** [comment]
I got stuck at the same error when I tried it about a year ago. I guess finding a linux box or emulating a x86 linux is the easiest solution.

**Comment by josephko91** [comment]
I was able to successfully compile pamtra on Mac. Documenting what I did here in case it's helpful for anyone else in the future.

- In addition to gcc, fftw, and netcdf, I had to also brew install netcdf-fortran (as @DaveOri suggested above)
- If you install (pandas, numpy, scipy, matplotlib, netcdf4) using conda, you need to add the paths to the include and lib directory to the FCFLAGS and LFLAGS line, respective. See in my original post for example. 
- I had to also modify the first line of the f2py3 script. You can find where this is by using the command `which f2py3`. I changed the path to point to my conda installation of python. E.g., `#!/Users/josephko/miniconda3/envs/pamtra/bin/python`
- additionally `tar xjf data.tar.bz2` was not working for me for some reason on my Mac. I had to use `tar -xzvf data.tar.bz2 -C ./data` to properly extract the data (make the 'data' dir first). 

It would be great it the Mac section of the pamtra documentation could be updated to reflect some of these. I had to do a lot of fiddling to get it to compile. Hopefully this saves someone some pain in the future :)
