### ISSUE TITLE
Mie calculations for non-spherical particles

### ISSUE THREAD

**Issue by DaveOri** [igmk/pamtra#8]
The mie-sphere scattering routine assumes the hydrometeors to be spheres with D=Dmax and density defined by either constant density or m-D relation.
A user raised the need to have Mie assuming not Dmax, but an effective D to make it volume-comparable with tmatrix calculations with aspect ratio != 1
This is already possible via a complicate parameter transformation that requires consistent changing of the PSD and density/m-D parameters.
I suggest to introduce two additional scattering methods:
mie-sphere-solid -> assumes a sphere of solid ice with the same mass of the hydrometeor
mie-spheroid-effective -> assumes a sphere that has the same volume of the spheroid the requested aspect ratio => Dmie^3 = ar * Dmax^3 (oblate) // Dmie^3 = ar^2 Dmax^3 (prolate)

**Comment by maahn** [comment]
Good idea!

**Comment by DaveOri** [comment]
Actually, after digging into the for issue #7 I realized that one can specify both the m-D relation in the form of a power law and the density of the scatterer. By doing so, the particle is assume to ha D=Dmax for everything related to PSD and fallspeed, but rho_eff=rho regarding scattering (and the code in this case adjust the size as effective spheroid). This is already the concept raised in the issue and might require just some testing and a proper example to be solved instead of a separated scattering method

**Comment by DaveOri** [comment]
I have tested this and apparently it works quite good.
Now I can also understand better why there are multiple diameter definitions in the code used at the same time (see diameter2scat or density2scat).
It would benefit (as the rest of the code) from some proper documentation, but I would consider it as solved
